# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-lKaE11BXnwduzf_ilXuSoYRT72G-E-9
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('student_feedback.csv')

df.head()

for col in df.columns:
    print(f"'{col}'")

df.columns = df.columns.str.strip()

rating_cols = df.columns[2:]

df[rating_cols].mean(numeric_only=True)

df['Average Rating'] = df[rating_cols].mean(axis=1)

df[['Student ID', 'Average Rating']].head()

import matplotlib.pyplot as plt

category_means = df[rating_cols].mean()

category_means.plot(kind='bar', color='skyblue')
plt.title("Average Rating per Feedback Category")
plt.ylabel("Average Rating (1 to 5)")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

df.to_csv("analyzed_feedback.csv", index=False)

from google.colab import files
files.download("analyzed_feedback.csv")

rating_cols = df.columns[2:]

df['Average Rating'] = df[rating_cols].mean(axis=1)

category_means = df[rating_cols].mean()

print(" STUDENT FEEDBACK DASHBOARD")
print("=====================================")
print(f"Total responses received: {len(df)}")
print(f"Average rating (all questions): {df['Average Rating'].mean():.2f}")
print("\nTop 3 Highest-Rated Areas:")
print(category_means.sort_values(ascending=False).head(3))

print("\nBottom 3 Lowest-Rated Areas:")
print(category_means.sort_values().head(3))

category_means.plot(kind='bar', color='lightgreen', figsize=(10, 5))
plt.title("Average Rating by Feedback Category")
plt.ylabel("Rating (1–5)")
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

# Define rating levels
def classify_rating(score):
    if score >= 4.0:
        return 'High (4–5)'
    elif score >= 3.0:
        return 'Medium (3–4)'
    else:
        return 'Low (<3)'

df['Rating Level'] = df['Average Rating'].apply(classify_rating)

# Plot
df['Rating Level'].value_counts().plot.pie(autopct='%1.1f%%', colors=['green', 'gold', 'red'])
plt.title("Student Satisfaction Levels")
plt.ylabel("")
plt.show()

df.to_csv("dashboard_results.csv", index=False)

from google.colab import files
files.download("dashboard_results.csv")